version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:24.04
    steps:
      - checkout
      - run: apt update -y && apt upgrade -y && apt install -y curl
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: . $HOME/.cargo/env
      - run: rustup install nightly
      - run: cargo install junitify
      - run: cargo +nightly test -- --format=json -Z unstable-options --report-time | junitify --out tests
      - store_test_results:
          path: tests

  test:
