version: 2.1

references:
  docker_hub_authentication: &docker_hub_authentication
    username: $DOCKER_HUB_USERNAME
    password: $DOCKER_HUB_PASSWORD

jobs:
  build:
    docker:
      - image: circleci/ubuntu-2404:2024.05.1
        <<: *docker_hub_authentication
    steps:
      - checkout
      - run: sudo apt update -y
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: source $HOME/.cargo/env
      - run: rustup install nightly
      - run: cargo install junitify
      - run: cargo +nightly test -- --format=json -Z unstable-options --report-time | junitify --out tests
      - store_test_results:
          path: tests

  test:
