version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:24.04
    steps:
      - checkout
      - run: apt update -y && apt upgrade -y && apt install -y curl build-essential
      - run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && bash ~/miniconda.sh -b -p $HOME/miniconda
      - run: eval "$($HOME/miniconda/bin/conda shell.bash hook)"
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: echo 'source $HOME/.cargo/env' >> "$BASH_ENV"
      - run: rustup install nightly
      - run: cargo install junitify
      - run: cargo +nightly test -- --format=json -Z unstable-options --report-time | junitify --out tests
      - store_test_results:
          path: tests

  test:
